CREATE TABLE IF NOT EXISTS endereco (
  id_endereco bigint generated by default as identity
        constraint id_endereco_pk
            primary key,
  logradouro varchar(450) NOT NULL,
  bairro	 varchar(100) NOT NULL,
  numero varchar(30) NOT NULL

);



CREATE TABLE IF NOT EXISTS cliente (
  id_cliente bigint generated by default as identity
        constraint id_cliente_pk
            primary key,
  nome varchar(250) NOT NULL,
  abertura DATE NOT NULL,
  id_endereco bigint
        constraint cliente_id_endereco_fk
            references endereco(id_endereco)
);
